export const DOCKERFILE_TEMPLATE_OPTIONS = [
    { label: ".NET", type: "dotnet" },
    { label: "Astro (Node)", type: "astro/node" },
    { label: "Astro (Static)", type: "astro/static" },
    { label: "Bun", type: "bun" },
    { label: "C/C++", type: "cpp" },
    { label: "Dart", type: "dart" },
    { label: "Deno", type: "deno" },
    { label: "Elixir", type: "elixir" },
    { label: "Go", type: "go" },
    { label: "Java (Gradle)", type: "java/gradle" },
    { label: "Java (Maven)", type: "java/maven" },
    { label: "NextJS (Server)", type: "nextjs/server" },
    { label: "NextJS (Standalone)", type: "nextjs/standalone" },
    { label: "NodeJS", type: "node" },
    { label: "NuxtJS (SSR)", type: "nuxt/ssr" },
    { label: "NuxtJS (Static)", type: "nuxt/static" },
    { label: "PHP", type: "php" },
    { label: "Python", type: "python" },
    { label: "R (Plumber)", type: "r/plumber" },
    { label: "R (Shiny)", type: "r/shiny" },
    { label: "Ruby", type: "ruby" },
    { label: "Rust", type: "rust" },
    { label: "Scala", type: "scala" },
    { label: "Static", type: "static" },
    { label: "Zig", type: "zig" },
] as const;
