export const ROUTING_SETTINGS_TEXT_CONTROL_MAX_WIDTH_CLASS = "w-full max-w-[600px]";
export const ROUTING_SETTINGS_COMPOUND_CONTROL_MAX_WIDTH_CLASS = "w-full max-w-[800px]";

export const HTTP_SETTINGS_TEXT_CONTROL_MAX_WIDTH_CLASS = ROUTING_SETTINGS_TEXT_CONTROL_MAX_WIDTH_CLASS;
export const HTTP_SETTINGS_COMPOUND_CONTROL_MAX_WIDTH_CLASS = ROUTING_SETTINGS_COMPOUND_CONTROL_MAX_WIDTH_CLASS;
