export const ESettingType = {
    None: "",
    Project: "project",
    App: "app",
    AppDeployment: "app-deployment",
    AppFeatures: "app-features",
    AppRouting: "app-routing",
    AcmeDnsProvider: "acme-dns-provider",
    EnvVar: "env-var",
    Secret: "secret",
    CloudStorage: "cloud-storage",
    OAuth: "oauth",
    SSHKey: "ssh-key",
    APIKey: "api-key",
    IMService: "im-service",
    RegistryAuth: "registry-auth",
    BasicAuth: "basic-auth",
    GithubApp: "github-app",
    AccessToken: "access-token",
    CommandTemplate: "command-template",
    CommandPipe: "command-pipe",
    SchedJob: "sched-job",
    Email: "email",
    RepoWebhook: "repo-webhook",
    Notification: "notification",
    HivePaaSService: "hivepaas-service",
    TraefikService: "traefik-service",
    SystemCleanup: "system-cleanup",
    SystemBackup: "system-backup",
    SSLRenewal: "ssl-renewal",
    BackupRepoCleanup: "backup-repo-cleanup",
    File: "file",
    ImageBuild: "image-build",
    SSLCert: "ssl-cert",
    SSLProvider: "ssl-provider",
    DomainSettings: "domain-settings",
    StorageSettings: "storage-settings",
    ClusterVolume: "cluster-volume",
    PeriodicJob: "periodic-job",
    BackupRepo: "backup-repo",
} as const;

export type ESettingType = (typeof ESettingType)[keyof typeof ESettingType];
